#!/usr/bin/env python3
# Copyright 2024 The ScenDroid Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Batch testing script for Scenario-Level evaluation.

This script allows you to test a specific agent across multiple scenarios
in a specified order, with automatic log saving after each scenario.

Examples:
    # Test qwen3vl-235b on all scenarios (default order: A, B, C, D, E, Omnilife)
    python run_scenario_batch.py --agent qwen3vl-235b
    
    # Test with custom scenario order
    python run_scenario_batch.py --agent qwen3vl-235b --scenarios omnilife e d c b a
    
    # Test specific scenarios (uses original instructions by default)
    python run_scenario_batch.py --agent qwen3vl-8b --scenarios a b c
    
    # Test with specific clarity level (L0/L1/L2 for obfuscated instructions)
    python run_scenario_batch.py --agent qwen3vl-235b-context --scenarios a b --level L0
    python run_scenario_batch.py --agent qwen3vl-235b-context --scenarios a b --level L1
    
    # Auto-confirm all prompts
    python run_scenario_batch.py --agent doubao --scenarios omnilife --auto_confirm
    
    # Specify emulator ports (useful for multiple emulator instances)
    python run_scenario_batch.py --agent qwen3vl-235b --scenarios a --console_port 5554 --grpc_port 8554
    
    # Use different emulator instance
    python run_scenario_batch.py --agent qwen3vl-8b --scenarios a b --console_port 5556 --grpc_port 8556 --auto_confirm
    
    # 🎯 Fast start from specific subtask (e.g., jump to Shopping task #7)
    python run_scenario_batch.py --agent qwen3vl-235b --scenarios a --start_from_subtask 7 --auto_confirm
    
    # Useful for debugging: batch initialization runs, but execution starts from subtask 7
    python run_scenario_batch.py --agent qwen3vl-8b --scenarios omnilife --start_from_subtask 15 --auto_confirm
    
Available agents:
    Single-Model:
      - qwen3vl-235b, qwen3vl-32b, qwen3vl-8b
    
    Additional agents (dual-model, context-enhanced, ask-enabled, etc.) 
    will be available in future releases. See README.md Roadmap for details.
    
Available scenarios:
    - a : Wake-up → Work Kickoff
    - b : Busy Monday for David
    - c : Shopping Scenario C
    - d : Shopping Scenario D
    - e : Shopping Scenario E
    - omnilife : Comprehensive OmniLife Scenario

Instruction types:
    - Default (no --level): Uses original scenario instructions (user_instruction)
    - L0 (--level L0): Uses fully specified instructions (user_instruction_L0)
    - L1 (--level L1): Uses partially obfuscated instructions (user_instruction_L1)
    - L2 (--level L2): Uses highly obfuscated instructions (user_instruction_L2)
"""

import os
import sys
import json
import time
import datetime
import argparse
import asyncio
from pathlib import Path
from typing import Optional, List, Dict, Any
import numpy as np  # 🆕 For screenshot handling

# Add webarena to path
webarena_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "webarena")
if os.path.exists(webarena_path) and webarena_path not in sys.path:
    sys.path.insert(0, webarena_path)

from scendroid.env import env_launcher
from scendroid.layered_task_loader import LayeredTaskLoader
from scendroid.task_evals.webarena import container_manager as cm
from scendroid.task_evals.webarena import port_utils  # 🆕 Import port mapping utility
from scendroid.agents import qwen3vl_agent
# Additional agent imports will be available in future releases.
# See the Roadmap section in README.md for details.
from scendroid.apps.registry import AppRegistry

# Suppress verbose logging
import logging
logging.basicConfig(level=logging.WARNING)
os.environ['GRPC_VERBOSITY'] = 'ERROR'
os.environ['GRPC_TRACE'] = 'none'

# Setup WebArena environment variable (default value; will be dynamically updated during scenario initialization)
os.environ.setdefault('SHOPPING', 'http://localhost:7770')
os.environ.setdefault('SHOPPING_ADMIN', 'http://localhost:7770/admin')
os.environ.setdefault('REDDIT', 'http://placeholder.com')
os.environ.setdefault('GITLAB', 'http://placeholder.com')
os.environ.setdefault('WIKIPEDIA', 'http://placeholder.com')
os.environ.setdefault('MAP', 'http://placeholder.com')
os.environ.setdefault('HOMEPAGE', 'http://placeholder.com')

# 🆕 Load Shopping mode configuration (generated by init_shopping_environment.sh)
def _load_shopping_config():
    """Loaded from Shopping-related environment variables in config"""
    config_file = "/tmp/shopping_mode.conf"
    if os.path.exists(config_file):
        try:
            with open(config_file, 'r') as f:
                for line in f:
                    line = line.strip()
                    # Skip comments and blank lines
                    if not line or line.startswith('#'):
                        continue
                    if '=' in line:
                        key, value = line.split('=', 1)
                        key = key.strip()
                        value = value.strip()
                        # set environment variables
                        if key in ['SHOPPING_MODE', 'SHOPPING_URL', 'SHOPPING', 'HOST_IP']:
                            os.environ[key] = value
                            if key == 'SHOPPING_URL':
                                # Also update SHOPPING environment variable
                                os.environ['SHOPPING'] = value
                            print(f"   📋 loaded from config: {key}={value}")
        except Exception as e:
            print(f"⚠️  Failed to read Shopping configuration file: {e}")

_load_shopping_config()

# ============================================================
# Agent Configuration
# ============================================================

# Qwen3-VL Configuration
QWEN_API_KEY = os.environ.get("DASHSCOPE_API_KEY", "")
QWEN_BASE_URL = os.environ.get("QWEN_BASE_URL", "https://dashscope.aliyuncs.com/compatible-mode/v1")
QWEN_MODEL_MAPPING = {
    "qwen3vl-235b": "qwen3-vl-235b-a22b-instruct",
    "qwen3vl-32b": "qwen3-vl-32b-instruct",  # 🔧 Fix: 32B model lacks the -a22b suffix
    "qwen3vl-8b": "qwen3-vl-8b-instruct",    # 🔧 Fix: 8B model lacks the -a22b suffix
}

# Additional agent configurations will be available in future releases.

# ============================================================
# Scenario Configuration
# ============================================================

SCENARIO_MAP = {
    "a": {"id": "A", "name": "Wake-up → Work Kickoff"},
    "b": {"id": "B", "name": "Busy Monday for David"},
    "c": {"id": "C", "name": "Shopping Scenario C"},
    "d": {"id": "D", "name": "Shopping Scenario D"},
    "e": {"id": "E", "name": "Shopping Scenario E"},
    "omnilife": {"id": "Omnilife", "name": "OmniLife Comprehensive"},
}

DEFAULT_SCENARIO_ORDER = ["a", "b", "c", "d", "e", "omnilife"]

# ============================================================
# Agent Factory
# ============================================================

def create_agent(agent_type: str, env, original_goal: str = "", human_sim=None):
    """Create agent instance based on agent type.
    
    Args:
        agent_type: Agent type identifier
        env: Android environment
        original_goal: Original task goal (for ask-enabled agents)
        human_sim: HumanSimulator instance (for ask-enabled agents)
    
    Returns:
        Agent instance
    """
    agent_name = f"BatchScenario-{agent_type}"
    
    # ===== Qwen3-VL Series =====
    if agent_type in ["qwen3vl-235b", "qwen3vl-32b", "qwen3vl-8b"]:
        model_id = QWEN_MODEL_MAPPING[agent_type]
        return qwen3vl_agent.QwenAgent(
            env=env,
            api_key=QWEN_API_KEY,
            base_url=QWEN_BASE_URL,
            model_id=model_id,
            name=agent_name,
            wait_after_action_seconds=2.0,
        )
    
    # ===== Additional agents (Coming Soon) =====
    # Context-enhanced, dual-model, ask-enabled, and other agent variants
    # will be available in future releases. See README.md Roadmap for details.
    
    else:
        raise ValueError(f"Unknown agent type: {agent_type}")


# ============================================================
# Scenario Evaluator Loader
# ============================================================

def load_scenario_evaluators():
    """Load all scenario evaluators using AppRegistry.
    
    This matches the approach used in run_layered_tui_test.py.
    Evaluators are registered in scendroid/apps/scenario/__init__.py
    """
    evaluators = {}
    
    # Import scenario modules to trigger registration
    try:
        from scendroid.apps import scenario  # noqa: F401
    except ImportError as e:
        print(f"⚠️  Failed to import scenario module: {e}")
        return evaluators
    
    # 1-day scenarios
    one_day_scenarios = [
        ('A', 'ScenarioA_BusyMonday', 'Busy Monday'),
        ('B', 'ScenarioB_RelaxedSaturday', 'Relaxed Saturday'),
        ('C', 'ScenarioC_StudentResearchDay', 'Student Research Day'),
        ('D', 'ScenarioD_TechConferenceTrip', 'Tech Conference Trip'),
        ('E', 'ScenarioE_WeekendHiking', 'Weekend Hiking & Photography'),
    ]
    
    # 7-day scenarios
    seven_day_scenarios = [
        ('Omnilife', 'ScenarioOmniLife_7Day', 'OmniLife Complete Life (7-Day)'),
    ]
    
    # Load 1-day scenarios
    for scenario_id, eval_name, display_name in one_day_scenarios:
        eval_class = AppRegistry.get_evaluator(eval_name)
        if eval_class:
            evaluators[scenario_id] = eval_class
        else:
            print(f"⚠️  {scenario_id}: {eval_name} not found in registry")
    
    # Load 7-day scenarios
    for scenario_id, eval_name, display_name in seven_day_scenarios:
        eval_class = AppRegistry.get_evaluator(eval_name)
        if eval_class:
            evaluators[scenario_id] = eval_class
        else:
            print(f"⚠️  {scenario_id}: {eval_name} not found in registry")
    
    return evaluators


# ============================================================
# Log Management
# ============================================================

class ScenarioLogger:
    """Enhanced logger with markdown reports and screenshot saving.
    
    Directory structure:
        scenario_logs/
        └── {agent}-{scenario}-{timestamp}/
            ├── report.md          (main markdown report)
            ├── screenshots/       (all step screenshots)
            │   ├── subtask_1_step_1.png
            │   ├── subtask_1_step_2.png
            │   └── ...
            └── metadata.json      (test metadata)
    """
    
    def __init__(self, log_dir: str = "./scenario_logs"):
        self.log_dir = Path(log_dir)
        self.log_dir.mkdir(exist_ok=True, parents=True)
        
        # Test session directory (created when test starts)
        self.session_dir = None
        self.screenshots_dir = None
        self.markdown_file = None
        
        # Logging state
        self.current_log = []
        self.markdown_content = []  # 🆕 Markdown content (retained for compatibility)
        self.start_time = None
        self.current_log_file = None  # Retain traditional text log
        self.log_file_handle = None
        self.markdown_file_handle = None  # 🆕 Markdown file handle (for real-time writing)
        
        # Screenshot tracking
        self.current_subtask_idx = None
        self.current_subtask_step = 0  # Step count for current subtask
        
        # Test metadata
        self.agent_type = None
        self.scenario_id = None
        self.scenario_name = None
    
    def start_scenario(self, agent_type: str, scenario_id: str, scenario_name: str):
        """Start logging a new scenario with enhanced directory structure."""
        # Close previous file handles if exist
        if self.log_file_handle:
            self.log_file_handle.close()
            self.log_file_handle = None
        if self.markdown_file_handle:  # 🆕 Also close markdown handle
            self.markdown_file_handle.close()
            self.markdown_file_handle = None
        
        # Save metadata
        self.agent_type = agent_type
        self.scenario_id = scenario_id
        self.scenario_name = scenario_name
        self.current_log = []
        self.markdown_content = []
        self.start_time = time.time()
        
        # 🆕 Create session directory
        timestamp = datetime.datetime.now().strftime('%Y%m%d_%H%M%S')
        session_name = f"{agent_type}-{scenario_id.lower()}-{timestamp}"
        self.session_dir = self.log_dir / session_name
        self.session_dir.mkdir(exist_ok=True, parents=True)
        
        # 🆕 Create screenshots subdirectory
        self.screenshots_dir = self.session_dir / "screenshots"
        self.screenshots_dir.mkdir(exist_ok=True)
        
        # 🆕 Create markdown report file
        self.markdown_file = self.session_dir / "report.md"
        
        # Create traditional text log file (for backward compatibility)
        filename = f"{agent_type}-{scenario_id.lower()}-{timestamp}.log"
        self.current_log_file = self.session_dir / filename
        
        # Open files for real-time writing
        self.log_file_handle = open(self.current_log_file, 'w', encoding='utf-8', buffering=1)
        self.markdown_file_handle = open(self.markdown_file, 'w', encoding='utf-8', buffering=1)  # 🆕 openmarkdownfile
        
        # Write initial header to text log
        start_datetime = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        self.log(f"{'='*80}")
        self.log(f"SCENARIO TEST: {scenario_id} - {scenario_name}")
        self.log(f"Agent: {agent_type}")
        self.log(f"Start Time: {start_datetime}")
        self.log(f"{'='*80}\n")
        
        # 🆕 Write initial markdown header (real-time write)
        self.write_markdown(f"# Scenario Test Report: {scenario_name}\n")
        self.write_markdown(f"## Test Information\n")
        self.write_markdown(f"- **Agent**: {agent_type}\n")
        self.write_markdown(f"- **Scenario**: {scenario_id} - {scenario_name}\n")
        self.write_markdown(f"- **Start Time**: {start_datetime}\n")
        self.write_markdown(f"\n---\n")
        
        print(f"\n📂 Session directory created: {self.session_dir}")
        print(f"📸 Screenshots will be saved to: {self.screenshots_dir}")
        print(f"📝 Markdown report: {self.markdown_file}\n")
    
    def log(self, message: str, also_print: bool = True):
        """Add a log message and write to file immediately.
        
        Args:
            message: Log message
            also_print: If True, also print to console (default: True)
        """
        timestamp = datetime.datetime.now().strftime('%H:%M:%S')
        log_entry = f"[{timestamp}] {message}"
        self.current_log.append(log_entry)
        
        if also_print:
            print(message)  # Print to console (without timestamp)
        
        # Write to file in real time
        if self.log_file_handle:
            self.log_file_handle.write(log_entry + '\n')
            self.log_file_handle.flush()  # Force refresh buffer to ensure immediate disk write
    
    def write_markdown(self, content: str):
        """Write markdown content to file immediately.
        
        Args:
            content: Markdown text to append
        """
        self.markdown_content.append(content)  # Keep in memory (for backup)
        
        # 🆕 Write to markdown file in real time
        if self.markdown_file_handle:
            self.markdown_file_handle.write(content)
            self.markdown_file_handle.flush()  # Force refresh to ensure immediate disk write
    
    def save_screenshot(self, screenshot_pixels: 'np.ndarray', subtask_idx: int, step_num: int) -> Optional[str]:
        """Save screenshot and return relative path for markdown.
        
        Args:
            screenshot_pixels: Screenshot as numpy array (from state.pixels)
            subtask_idx: Current subtask index (0-based)
            step_num: Current step number within subtask
            
        Returns:
            Relative path to screenshot (for markdown) or None if failed
        """
        if screenshot_pixels is None or self.screenshots_dir is None:
            return None
        
        try:
            from PIL import Image
            
            # Generate filename
            filename = f"subtask_{subtask_idx + 1}_step_{step_num}.png"
            screenshot_path = self.screenshots_dir / filename
            
            # Convert numpy array to PIL Image and save
            img = Image.fromarray(screenshot_pixels)
            img.save(screenshot_path)
            
            # Return relative path for markdown (relative to report.md location)
            relative_path = f"screenshots/{filename}"
            return relative_path
            
        except Exception as e:
            logging.warning(f"⚠️  Failed to save screenshot: {e}")
            return None
    
    def log_subtask_start(self, subtask_idx: int, subtask_name: str, instruction: str, 
                          instruction_type: str = "Original"):
        """Log subtask start with markdown formatting."""
        # Update current subtask tracking
        self.current_subtask_idx = subtask_idx
        self.current_subtask_step = 0  # Reset step counter for new subtask
        
        # Traditional log
        self.log(f"\n{'─'*80}")
        self.log(f"📍 SUBTASK {subtask_idx + 1}: {subtask_name}")
        self.log(f"Instruction Type: {instruction_type}")
        self.log(f"Instruction: {instruction}")
        self.log(f"{'─'*80}")
        
        # 🆕 Markdown content (real-time write)
        self.write_markdown(f"\n## Subtask {subtask_idx + 1}: {subtask_name}\n")
        self.write_markdown(f"- **Instruction Type**: {instruction_type}\n")
        self.write_markdown(f"- **Instruction**: {instruction}\n")
        self.write_markdown(f"\n")
    
    def log_subtask_result(self, subtask_idx: int, success: bool, score: float, 
                           details: str = "", step_details: List[Dict] = None,
                           ask_count: int = 0, total_steps: int = 0):
        """Log subtask result with detailed step information and screenshots.
        
        Args:
            subtask_idx: Subtask index
            success: Whether subtask succeeded
            score: Subtask score
            details: Summary details
            step_details: List of step details with:
                - step: step number
                - thought: agent's reasoning
                - action: action description
                - tool_call: tool call details
                - screenshot_path: (optional) relative path to screenshot
            ask_count: Number of clarification questions asked (for ask-enabled agents)
            total_steps: Total steps including ask steps
        """
        status = "✅ PASS" if success else "❌ FAIL"
        
        # Traditional log
        self.log(f"\n{'='*80}")
        self.log(f"{status} | Subtask {subtask_idx + 1} | Score: {score:.2f}")
        if details:
            self.log(f"Summary: {details}")
        
        # 📊 Record ask statistics
        if ask_count > 0 or total_steps > 0:
            self.log(f"\n📊 Task Statistics:")
            if total_steps > 0:
                self.log(f"  • Total steps: {total_steps}")
            if ask_count > 0:
                self.log(f"  • Questions asked: {ask_count}")
                if total_steps > 0:
                    ask_ratio = (ask_count / total_steps) * 100
                    self.log(f"  • Ask ratio: {ask_count}/{total_steps} ({ask_ratio:.1f}%)")
        
        # Log detailed step information to text log
        if step_details:
            self.log(f"\n📝 Detailed Step History ({len(step_details)} steps):")
            self.log(f"{'─'*80}")
            for step_info in step_details:
                step_num = step_info.get('step', 0)
                action_type = step_info.get('action_type', '')
                thought = step_info.get('thought', '')
                action = step_info.get('action', '')
                tool_call = step_info.get('tool_call', '')
                question = step_info.get('question', '')
                answer = step_info.get('answer', '')
                
                self.log(f"\nStep {step_num}:")
                
                # 🆕 If it is an ask-type, prioritize displaying the question and answer
                if action_type == 'ask':
                    if question:
                        self.log(f"  ❓ Question: {question}")
                    if answer:
                        self.log(f"  💬 Answer: {answer}")
                
                if thought:
                    self.log(f"  💭 Thought: {thought}")
                if action:
                    self.log(f"  🎯 Action: {action}")
                if tool_call:
                    self.log(f"  🔧 Tool: {tool_call}")
        
        self.log(f"{'='*80}\n")
        
        # 🆕 Markdown content with screenshots (real-time write)
        status_emoji = "✅" if success else "❌"
        self.write_markdown(f"- **Status**: {status_emoji} {'PASS' if success else 'FAIL'}\n")
        self.write_markdown(f"- **Score**: {score:.2f}\n")
        if details:
            self.write_markdown(f"- **Summary**: {details}\n")
        
        # 📊 Record ask statistics to markdown
        if ask_count > 0 or total_steps > 0:
            self.write_markdown(f"\n**📊 Task Statistics:**\n")
            if total_steps > 0:
                self.write_markdown(f"- Total steps: {total_steps}\n")
            if ask_count > 0:
                self.write_markdown(f"- Questions asked: {ask_count}\n")
                if total_steps > 0:
                    ask_ratio = (ask_count / total_steps) * 100
                    self.write_markdown(f"- Ask ratio: {ask_count}/{total_steps} ({ask_ratio:.1f}%)\n")
        
        # Add detailed steps to markdown
        if step_details:
            self.write_markdown(f"\n### Execution Steps ({len(step_details)} steps)\n")
            for step_info in step_details:
                step_num = step_info.get('step', 0)
                action_type = step_info.get('action_type', '')
                thought = step_info.get('thought', '')
                action = step_info.get('action', '')
                tool_call = step_info.get('tool_call', '')
                question = step_info.get('question', '')
                answer = step_info.get('answer', '')
                screenshot_path = step_info.get('screenshot_path', None)
                
                self.write_markdown(f"\n#### Step {step_num}\n")
                
                # 🆕 If it is an ask-type, prioritize displaying the question and answer
                if action_type == 'ask':
                    if question:
                        self.write_markdown(f"❓ **Question**: {question}\n\n")
                    if answer:
                        self.write_markdown(f"💬 **Answer**: {answer}\n\n")
                
                if thought:
                    self.write_markdown(f"💭 **Thought**: {thought}\n\n")
                if action:
                    self.write_markdown(f"🎯 **Action**: {action}\n\n")
                if tool_call:
                    # Escape potential markdown characters in tool call
                    tool_call_escaped = tool_call.replace('|', '\\|')
                    self.write_markdown(f"🔧 **Tool Call**: `{tool_call_escaped}`\n\n")
                
                # 🆕 Embed screenshot in markdown
                if screenshot_path:
                    self.write_markdown(f"![Step {step_num} Screenshot]({screenshot_path})\n\n")
        
        self.write_markdown(f"\n---\n")
    
    def save_log(self, agent_type: str, scenario_id: str, final_score: float, 
                 success: bool, subtask_results: List[Dict]):
        """Finalize log with summary, save markdown report and metadata."""
        if not self.start_time:
            return
        
        # Calculate duration
        duration = time.time() - self.start_time
        end_datetime = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        
        # 📊 Aggregate ask information for the entire scenario
        total_ask_count = sum(result.get('ask_count', 0) for result in subtask_results if not result.get('skipped', False))
        total_steps_count = sum(result.get('total_steps', 0) for result in subtask_results if not result.get('skipped', False))
        completed_subtasks = sum(1 for result in subtask_results if not result.get('skipped', False))
        
        # 📊 Compute the average ask ratio across all tasks
        task_ask_ratios = []
        for result in subtask_results:
            if not result.get('skipped', False):
                task_steps = result.get('total_steps', 0)
                task_asks = result.get('ask_count', 0)
                if task_steps > 0:
                    task_ratio = (task_asks / task_steps) * 100
                    task_ask_ratios.append(task_ratio)
        
        avg_task_ask_ratio = sum(task_ask_ratios) / len(task_ask_ratios) if task_ask_ratios else 0.0
        
        # Add summary to text log
        self.log(f"\n{'='*80}")
        self.log(f"SCENARIO SUMMARY")
        self.log(f"{'='*80}")
        self.log(f"Final Score: {final_score:.2f}")
        self.log(f"Status: {'✅ PASS' if success else '❌ FAIL'}")
        self.log(f"Duration: {duration:.1f}s ({duration/60:.1f} min)")
        
        # 📊 Add ask statistics for the entire scenario
        if total_ask_count > 0 or total_steps_count > 0:
            self.log(f"\n📊 Scenario Statistics:")
            self.log(f"  • Completed subtasks: {completed_subtasks}")
            if total_steps_count > 0:
                self.log(f"  • Total steps (all subtasks): {total_steps_count}")
            if total_ask_count > 0:
                self.log(f"  • Total questions asked: {total_ask_count}")
                if total_steps_count > 0:
                    scenario_ask_ratio = (total_ask_count / total_steps_count) * 100
                    self.log(f"  • Overall ask ratio (scenario-level): {total_ask_count}/{total_steps_count} ({scenario_ask_ratio:.1f}%)")
                # 📊 Add the average ask ratio per task
                if task_ask_ratios:
                    self.log(f"  • Average ask ratio per task: {avg_task_ask_ratio:.1f}% (across {len(task_ask_ratios)} tasks with steps)")
        
        self.log(f"\nSubtask Breakdown:")
        self.log(f"{'='*80}")
        for i, result in enumerate(subtask_results):
            status = "✅" if result.get('success', False) else "❌"
            subtask_info = f"  {status} Subtask {i+1}: {result.get('score', 0.0):.2f} - {result.get('name', 'Unknown')}"
            
            # 📊 Display steps and ask information in each subtask summary
            task_steps = result.get('total_steps', 0)
            task_asks = result.get('ask_count', 0)
            
            if task_steps > 0 or task_asks > 0:
                stats_parts = []
                if task_steps > 0:
                    stats_parts.append(f"{task_steps} steps")
                if task_asks > 0:
                    stats_parts.append(f"{task_asks} asks")
                subtask_info += f" [{', '.join(stats_parts)}]"
            
            self.log(subtask_info)
        self.log(f"{'='*80}\n")
        
        # 🆕 Add summary to markdown (real-time write)
        status_emoji = "✅" if success else "❌"
        self.write_markdown(f"\n## Test Summary\n")
        self.write_markdown(f"- **Final Score**: {final_score:.2f}\n")
        self.write_markdown(f"- **Status**: {status_emoji} {'PASS' if success else 'FAIL'}\n")
        self.write_markdown(f"- **End Time**: {end_datetime}\n")
        self.write_markdown(f"- **Duration**: {duration:.1f} seconds ({duration/60:.1f} minutes)\n")
        
        # 📊 Add ask statistics for the entire scenario to markdown
        if total_ask_count > 0 or total_steps_count > 0:
            self.write_markdown(f"\n### 📊 Scenario Statistics\n")
            self.write_markdown(f"- **Completed subtasks**: {completed_subtasks}\n")
            if total_steps_count > 0:
                self.write_markdown(f"- **Total steps** (all subtasks): {total_steps_count}\n")
            if total_ask_count > 0:
                self.write_markdown(f"- **Total questions asked**: {total_ask_count}\n")
                if total_steps_count > 0:
                    scenario_ask_ratio = (total_ask_count / total_steps_count) * 100
                    self.write_markdown(f"- **Overall ask ratio** (scenario-level): {total_ask_count}/{total_steps_count} ({scenario_ask_ratio:.1f}%)\n")
                # 📊 Add the average ask ratio per task
                if task_ask_ratios:
                    self.write_markdown(f"- **Average ask ratio per task**: {avg_task_ask_ratio:.1f}% (across {len(task_ask_ratios)} tasks with steps)\n")
        
        self.write_markdown(f"\n### Subtask Results\n")
        self.write_markdown(f"| Subtask | Name | Status | Score | Steps | Asks |\n")
        self.write_markdown(f"|---------|------|--------|-------|-------|------|\n")
        
        for i, result in enumerate(subtask_results):
            status = "✅" if result.get('success', False) else "❌"
            score = result.get('score', 0.0)
            name = result.get('name', 'Unknown')
            steps_display = result.get('total_steps', 0) if result.get('total_steps', 0) > 0 else "-"
            ask_count_display = result.get('ask_count', 0) if result.get('ask_count', 0) > 0 else "-"
            self.write_markdown(f"| {i+1} | {name} | {status} | {score:.2f} | {steps_display} | {ask_count_display} |\n")
        
        # 🆕 Close markdown file handle (already written in real time; only closing is needed)
        if self.markdown_file_handle:
            self.markdown_file_handle.close()
            self.markdown_file_handle = None
            print(f"📝 Markdown report finalized: {self.markdown_file}")
        
        # 🆕 Save metadata as JSON
        metadata = {
            "agent": agent_type,
            "scenario_id": scenario_id,
            "scenario_name": self.scenario_name,
            "start_time": datetime.datetime.fromtimestamp(self.start_time).strftime('%Y-%m-%d %H:%M:%S'),
            "end_time": end_datetime,
            "duration_seconds": duration,
            "final_score": final_score,
            "success": success,
            "subtask_count": len(subtask_results),
            "subtasks": subtask_results,
            # 📊 Add ask statistics
            "statistics": {
                "completed_subtasks": completed_subtasks,
                "total_steps": total_steps_count,
                "total_questions_asked": total_ask_count,
                "overall_ask_ratio_scenario_level": f"{total_ask_count}/{total_steps_count} ({(total_ask_count/total_steps_count*100):.1f}%)" if total_steps_count > 0 else "N/A",
                "average_ask_ratio_per_task": f"{avg_task_ask_ratio:.1f}%" if task_ask_ratios else "N/A",
                "tasks_with_steps_count": len(task_ask_ratios)
            }
        }
        
        metadata_file = self.session_dir / "metadata.json"
        try:
            with open(metadata_file, 'w', encoding='utf-8') as f:
                json.dump(metadata, f, indent=2, ensure_ascii=False)
            print(f"📊 Metadata saved: {metadata_file}")
        except Exception as e:
            logging.error(f"❌ Failed to save metadata: {e}")
        
        # Close text log file handle
        if self.log_file_handle:
            self.log_file_handle.close()
            self.log_file_handle = None
        
        print(f"\n💾 Text log saved: {self.current_log_file}")
        print(f"📂 Full session directory: {self.session_dir}\n")
        
        return self.session_dir
    
    def __del__(self):
        """Ensure file handles are closed when logger is destroyed."""
        if self.log_file_handle:
            self.log_file_handle.close()
        if self.markdown_file_handle:  # 🆕 Also close markdown handle
            self.markdown_file_handle.close()


# ============================================================
# Scenario Test Runner
# ============================================================

class ScenarioTestRunner:
    """Runner for batch scenario testing."""
    
    def __init__(self, agent_type: str, scenarios: List[str], 
                 clarity_level: str = None, auto_confirm: bool = False,
                 console_port: int = 5554, grpc_port: int = 8554,
                 start_from_subtask: int = None, reset_mode: bool = False):
        self.agent_type = agent_type
        self.scenarios = scenarios
        self.clarity_level = clarity_level  # None = use original instruction, L0/L1/L2 = use obfuscated
        self.auto_confirm = auto_confirm
        self.console_port = console_port
        self.grpc_port = grpc_port
        self.start_from_subtask = start_from_subtask  # 🎯 Fast start mode
        self.reset_mode = reset_mode  # ⚡ Per-Task Reset mode
        
        self.env = None
        self.container_mgr = None
        self.evaluators = {}
        self.logger = ScenarioLogger()
        
        # Test results
        self.results = []
    
    async def initialize(self):
        """Initialize environment and load evaluators."""
        print("\n" + "="*80)
        print("🚀 SCENARIO BATCH TEST - INITIALIZATION")
        print("="*80)
        print(f"Agent: {self.agent_type}")
        print(f"Scenarios: {', '.join([s.upper() for s in self.scenarios])}")
        
        # ⚡ Reset mode has highest priority
        if self.reset_mode:
            print(f"⚡ Execution Mode: Per-Task Reset (Forced L0 instructions)")
            print(f"   - Each task independently initialized")
            print(f"   - No state persistence between tasks")
            print(f"   - No task dependencies")
        else:
            level_display = self.clarity_level if self.clarity_level else "Original (Default)"
            print(f"📚 Execution Mode: Scenario (Batch initialization)")
            print(f"   Instruction Type: {level_display}")
        
        print(f"Console Port: {self.console_port}")
        print(f"gRPC Port: {self.grpc_port}")
        if self.start_from_subtask is not None:
            print(f"🎯 Fast Start Mode: Starting from Subtask {self.start_from_subtask}")
        print("="*80 + "\n")
        
        if not self.auto_confirm:
            response = input("Continue? (y/n): ")
            if response.lower() != 'y':
                print("❌ Aborted by user")
                sys.exit(0)
        
        # Load evaluators
        print("📦 Loading scenario evaluators...")
        self.evaluators = load_scenario_evaluators()
        print(f"✅ Loaded {len(self.evaluators)} scenario evaluators\n")
        
        # Initialize environment
        print(f"🔧 Initializing Android environment (console:{self.console_port}, grpc:{self.grpc_port})...")
        adb_path = self._find_adb_directory()
        self.env = env_launcher.load_and_setup_env(
            console_port=self.console_port,
            emulator_setup=False,
            freeze_datetime=False,
            adb_path=adb_path,
            grpc_port=self.grpc_port
        )
        print("✅ Environment initialized\n")
        
        # Initialize container manager (for WebArena scenarios)
        if any(s in ["c", "d", "e", "omnilife"] for s in self.scenarios):
            print(f"🐳 Initializing WebArena container manager (console:{self.console_port})...")
            self.container_mgr = cm.ShoppingContainerManager(console_port=self.console_port)
            
            # 🆕 Dynamically update environment variable to reflect correct port mapping
            # Compute mapping: 5554→7770, 5556→7772, 5558→7774, 5560→7776
            shopping_url = port_utils.get_shopping_base_url(console_port=self.console_port)
            shopping_admin_url = port_utils.get_shopping_admin_url(console_port=self.console_port)
            
            # Update environment variable (assign directly via os.environ, not setdefault)
            os.environ['SHOPPING'] = shopping_url
            os.environ['SHOPPING_ADMIN'] = shopping_admin_url
            
            print(f"🌐 Dynamic port mapping applied:")
            print(f"   Console Port: {self.console_port}")
            print(f"   Shopping URL: {shopping_url}")
            print(f"   Shopping Admin: {shopping_admin_url}")
            print("✅ Container manager initialized\n")
    
    async def run_all_scenarios(self):
        """Run all scenarios in order."""
        for i, scenario_key in enumerate(self.scenarios):
            print(f"\n{'='*80}")
            print(f"📊 PROGRESS: Scenario {i+1}/{len(self.scenarios)}")
            print(f"{'='*80}\n")
            
            try:
                result = await self.run_single_scenario(
                    scenario_key, 
                    start_from_subtask=self.start_from_subtask
                )
                self.results.append(result)
                
                # Wait between scenarios
                if i < len(self.scenarios) - 1:
                    print(f"\n⏳ Waiting 10 seconds before next scenario...")
                    await asyncio.sleep(10)
            
            except Exception as e:
                print(f"\n❌ ERROR in scenario {scenario_key}: {e}")
                import traceback
                traceback.print_exc()
                
                # Log error
                self.logger.log(f"ERROR: {str(e)}")
                self.logger.save_log(
                    self.agent_type, 
                    scenario_key.upper(), 
                    0.0, 
                    False, 
                    []
                )
                
                # Record failed result
                self.results.append({
                    "scenario": scenario_key.upper(),
                    "success": False,
                    "score": 0.0,
                    "error": str(e),
                })
    
    async def run_single_scenario(self, scenario_key: str, start_from_subtask: int = None) -> Dict:
        """Run a single scenario test.
        
        Args:
            scenario_key: Scenario key (lowercase, e.g., "a", "omnilife")
            start_from_subtask: Optional subtask ID to start from (1-based). 
                               If specified, batch initialization still runs, 
                               but execution jumps to this subtask.
        
        Returns:
            Dictionary with test results
        """
        # Get scenario info
        if scenario_key not in SCENARIO_MAP:
            raise ValueError(f"Unknown scenario: {scenario_key}")
        
        scenario_info = SCENARIO_MAP[scenario_key]
        scenario_id = scenario_info["id"]
        scenario_name = scenario_info["name"]
        
        # Check if evaluator exists
        if scenario_id not in self.evaluators:
            raise ValueError(f"Evaluator not found for scenario {scenario_id}")
        
        # Start logging
        self.logger.start_scenario(self.agent_type, scenario_id, scenario_name)
        
        # Create evaluator instance with clarity_level and reset_mode
        evaluator_class = self.evaluators[scenario_id]
        evaluator_params = {
            'clarity_level': self.clarity_level,  # Pass clarity level
            'reset_mode': self.reset_mode,  # ⚡ Pass reset mode
        }
        evaluator = evaluator_class(evaluator_params)
        
        # Check if scenario supports layered instructions
        if self.clarity_level is not None:
            supports_layers = self._check_layered_support(evaluator)
            if not supports_layers:
                warning_msg = (
                    f"⚠️  NOTICE: Scenario '{scenario_id}' does not have L0/L1/L2 instructions.\n"
                    f"   Requested level: {self.clarity_level}\n"
                    f"   Falling back to original instructions (user_instruction)."
                )
                print(f"\n\033[33m{warning_msg}\033[0m\n")  # Yellow warning
                self.logger.log(warning_msg)
                # Continue execution with original instructions (clarity_level will be ignored)
        
        # Initialize scenario
        self.logger.log("🔧 Initializing scenario environment...")
        try:
            # Run blocking initialize_task in executor (it's not async)
            loop = asyncio.get_event_loop()
            await loop.run_in_executor(
                None,
                evaluator.initialize_task,
                self.env
            )
            self.logger.log("✅ Scenario initialized\n")
        except Exception as e:
            self.logger.log(f"⚠️  Scenario initialization failed: {e}\n")
            import traceback
            traceback.print_exc()
        
        # Create agent
        self.logger.log(f"🤖 Creating agent: {self.agent_type}")
        
        # HumanSimulator for ask-enabled agents (coming in future release)
        human_sim = None
        
        agent = create_agent(self.agent_type, self.env, original_goal="", human_sim=human_sim)
        
        # Clear scenario context if supported
        if hasattr(agent, 'clear_scenario_context'):
            agent.clear_scenario_context()
        
        self.logger.log("✅ Agent created\n")
        
        # Execute all subtasks
        subtask_results = []
        total_subtasks = len(evaluator.subtasks)
        
        # 🎯 Check if we should start from a specific subtask
        start_idx = 0
        if start_from_subtask is not None:
            # Convert to 0-based index
            start_idx = start_from_subtask - 1
            if start_idx < 0 or start_idx >= total_subtasks:
                warning_msg = (
                    f"⚠️  WARNING: Invalid subtask ID {start_from_subtask}. "
                    f"Valid range: 1-{total_subtasks}. Starting from subtask 1."
                )
                print(f"\n\033[33m{warning_msg}\033[0m\n")
                self.logger.log(warning_msg)
                start_idx = 0
            else:
                skip_msg = (
                    f"\n{'='*80}\n"
                    f"⏭️  FAST START MODE\n"
                    f"{'='*80}\n"
                    f"   • Batch initialization: ✅ Completed\n"
                    f"   • Skipping subtasks: 1-{start_from_subtask - 1}\n"
                    f"   • Starting from: Subtask {start_from_subtask}\n"
                    f"   • Total subtasks: {total_subtasks}\n"
                    f"{'='*80}\n"
                )
                print(f"\033[36m{skip_msg}\033[0m")  # Cyan info
                self.logger.log(skip_msg)
        
        for subtask_idx in range(total_subtasks):
            subtask = evaluator.subtasks[subtask_idx]
            subtask_name = subtask.get("evaluator_name", f"Subtask {subtask_idx + 1}")
            
            # 🎯 Skip subtasks before start_idx
            if subtask_idx < start_idx:
                skip_msg = f"⏭️  Skipping Subtask {subtask_idx + 1}: {subtask_name}"
                print(f"\033[90m{skip_msg}\033[0m")  # Gray
                self.logger.log(skip_msg)
                
                # Add placeholder result for skipped subtasks
                subtask_results.append({
                    "subtask_id": subtask_idx + 1,
                    "subtask_name": subtask_name,
                    "instruction": "(skipped)",
                    "success": None,
                    "score": 0.0,
                    "steps": 0,
                    "duration": 0.0,
                    "skipped": True
                })
                continue
            
            # Get instruction based on clarity level (pass level explicitly like TUI does)
            instruction = evaluator.get_subtask_instruction(subtask_idx, level=self.clarity_level)
            
            # Determine actual instruction type used
            actual_level = "Original"
            if self.clarity_level is not None and self._check_layered_support(evaluator):
                actual_level = self.clarity_level
            elif self.clarity_level is not None:
                actual_level = f"Original (requested {self.clarity_level}, not supported)"
            
            self.logger.log_subtask_start(subtask_idx, subtask_name, instruction, actual_level)
            
            # 🆕 Reset agent before each subtask (critical for clearing history)
            # This matches the behavior in run_layered_tui_test.py (Line 1527, 1945, 2452)
            # Note: Different agents have different reset() signatures:
            #   - GUI-Owl: reset(go_home=False)
            #   - Qwen3-VL: reset(go_home_on_reset=False)
            #   - GELab-Zero: reset(goal=None)
            # Solution: Call without arguments (all have default values)
            if hasattr(agent, 'reset'):
                agent.reset()
                self.logger.log("🔄 Agent reset: history cleared\n")
            
            # Execute subtask
            try:
                subtask_result = await self.execute_subtask(
                    agent, evaluator, subtask_idx, instruction
                )
                subtask_results.append(subtask_result)
                
                self.logger.log_subtask_result(
                    subtask_idx,
                    subtask_result['success'],
                    subtask_result['score'],
                    subtask_result.get('details', ''),
                    subtask_result.get('step_details', []),
                    subtask_result.get('ask_count', 0),
                    subtask_result.get('total_steps', 0)
                )
                
                # Add completed task to context if supported
                if hasattr(agent, 'add_completed_task_to_scenario_context'):
                    agent.add_completed_task_to_scenario_context(
                        subtask_name, instruction
                    )
            
            except Exception as e:
                self.logger.log(f"❌ Error in subtask: {e}")
                import traceback
                traceback.print_exc()
                
                subtask_results.append({
                    "name": subtask_name,
                    "success": False,
                    "score": 0.0,
                    "error": str(e),
                })
        
        # Evaluate overall scenario
        self.logger.log("\n📊 Evaluating overall scenario...")
        final_score = evaluator.evaluate(self.env)
        success = final_score >= 0.8  # 80% threshold
        
        # Save log
        log_path = self.logger.save_log(
            self.agent_type, scenario_id, final_score, success, subtask_results
        )
        
        return {
            "scenario": scenario_id,
            "name": scenario_name,
            "success": success,
            "score": final_score,
            "subtask_results": subtask_results,
            "log_path": str(log_path),
        }
    
    async def execute_subtask(self, agent, evaluator, subtask_idx: int, 
                              instruction: str) -> Dict:
        """Execute a single subtask with the agent.
        
        Args:
            agent: Agent instance
            evaluator: Scenario evaluator
            subtask_idx: Subtask index
            instruction: Task instruction
        
        Returns:
            Dictionary with subtask result
        """
        subtask = evaluator.subtasks[subtask_idx]
        max_steps = subtask.get("max_steps", 20)
        
        # 🆕 For ask-enabled agents, update original_goal to L0 instruction
        if hasattr(agent, 'original_goal'):
            # Try to get L0 instruction as ground truth
            try:
                l0_instruction = evaluator.get_subtask_instruction(subtask_idx, level="L0")
                agent.original_goal = l0_instruction
                self.logger.log(f"📝 Updated agent's original_goal (L0) for ask functionality\n")
            except:
                # Fallback to current instruction if L0 not available
                agent.original_goal = instruction
                self.logger.log(f"📝 Updated agent's original_goal (fallback) for ask functionality\n")
        
        # Initialize subtask
        self.logger.log("🔧 Initializing subtask...")
        try:
            # Run blocking initialize_subtask in executor (it's not async)
            loop = asyncio.get_event_loop()
            await loop.run_in_executor(
                None,
                evaluator.initialize_subtask,
                subtask_idx,
                self.env
            )
            self.logger.log("✅ Subtask initialized\n")
        except Exception as e:
            self.logger.log(f"⚠️  Subtask initialization failed: {e}\n")
            import traceback
            traceback.print_exc()
        
        self.logger.log(f"🏃 Executing with agent (max {max_steps} steps)...")
        self.logger.log("")  # Empty line for readability
        
        step_count = 0
        done = False
        step_details = []  # Store detailed step information
        
        while step_count < max_steps and not done:
            step_count += 1
            
            # Print step header in terminal (with color)
            step_header = f"{'─'*80}\n📍 Step {step_count}/{max_steps}\n{'─'*80}"
            print(f"\033[36m{step_header}\033[0m")  # Cyan color
            self.logger.log(step_header)
            
            try:
                # Agent step
                response = agent.step(instruction)
                
                # Extract thought and action from response
                thought = ""
                action = ""
                action_type = ""
                tool_call = ""
                model_output = ""  # 🆕 Raw model output
                dual_instruction = ""  # 🆕 Instruction for dual model
                
                # 🆕 Dual-model-specific field (initialize is empty)
                planner_reasoning = ""
                planner_instruction = ""
                executor_thought = ""
                executor_action = ""
                
                # 🆕 Ask-specific field (initialize is empty)
                question = ""
                answer = ""
                
                if hasattr(response, 'data') and response.data:
                    thought = response.data.get('thought', '')
                    action = response.data.get('action_description', '')
                    action_type = response.data.get('action_type', '')
                    tool_call = response.data.get('tool_call_raw', '')
                    model_output = response.data.get('action_output', '')  # Original output
                    
                    # 🆕 For dual model, extract additional information
                    # dual_context_agent uses: planner_reasoning, planner_instruction, executor_thought, executor_action
                    planner_reasoning = response.data.get('planner_reasoning', '')
                    planner_instruction = response.data.get('planner_instruction', '')
                    executor_thought = response.data.get('executor_thought', '')
                    executor_action = response.data.get('executor_action', '')
                    
                    # 🆕 For ask agent, extract the question and answer
                    question = response.data.get('question', '')
                    answer = response.data.get('answer', '')
                    
                    # Set up dual_instruction (preferentially use planner_instruction)
                    dual_instruction = planner_instruction or response.data.get('instruction', '')
                
                # Print to terminal with formatting
                # 🆕 Distinguish output types: ask, dual model, single model
                is_ask_action = (action_type == 'ask')
                is_dual_model = bool(planner_reasoning or planner_instruction)
                
                if is_ask_action:
                    # Ask mode: display the question and answer
                    if question:
                        question_output = f"❓ Question: {question}"
                        print(f"\033[33m{question_output}\033[0m")  # Yellow
                        self.logger.log(question_output, also_print=False)
                    
                    if answer:
                        answer_output = f"💬 Answer: {answer}"
                        print(f"\033[32m{answer_output}\033[0m")  # Green
                        self.logger.log(answer_output, also_print=False)
                    
                    if action:
                        action_output = f"🎯 Action: {action}"
                        print(f"\033[36m{action_output}\033[0m")  # Cyan
                        self.logger.log(action_output, also_print=False)
                
                elif is_dual_model:
                    # Dual Model: output only the Planner and Executor fields
                    if planner_reasoning:
                        reasoning_output = f"🧠 Planner Reasoning: {planner_reasoning}"
                        print(f"\033[35m{reasoning_output}\033[0m")  # Magenta (colored)
                        self.logger.log(reasoning_output, also_print=False)  # Log only, do not print
                    
                    if planner_instruction:
                        instruction_output = f"📋 Planner Instruction: {planner_instruction}"
                        print(f"\033[36m{instruction_output}\033[0m")  # Cyan
                        self.logger.log(instruction_output, also_print=False)
                    
                    if executor_thought:
                        exec_thought = f"💡 Executor Thought: {executor_thought}"
                        print(f"\033[33m{exec_thought}\033[0m")  # Yellow
                        self.logger.log(exec_thought, also_print=False)
                    
                    if executor_action:
                        exec_action = f"⚡ Executor Action: {executor_action}"
                        print(f"\033[32m{exec_action}\033[0m")  # Green
                        self.logger.log(exec_action, also_print=False)
                else:
                    # Single model: output only thought and action
                    if thought:
                        thought_output = f"💭 Thought: {thought}"
                        print(f"\033[33m{thought_output}\033[0m")  # Yellow
                        self.logger.log(thought_output, also_print=False)
                    
                    if action:
                        action_output = f"🎯 Action: {action}"
                        print(f"\033[32m{action_output}\033[0m")  # Green
                        self.logger.log(action_output, also_print=False)
                
                # Tool Call (output by all models)
                if tool_call:
                    tool_output = f"🔧 Tool Call: {tool_call}"
                    print(f"\033[90m{tool_output}\033[0m")  # Gray color
                    self.logger.log(tool_output, also_print=False)
                
                # 🆕 Original model output is no longer logged (too long and unnecessary)
                # if model_output:
                #     self.logger.log(f"📤 Model Output (raw): {model_output[:500]}...")
                
                # 🆕 Save screenshot and get relative path  
                screenshot_path = None
                raw_screenshot = None
                if hasattr(response, 'data') and response.data:
                    raw_screenshot = response.data.get('raw_screenshot', None)
                
                if raw_screenshot is not None:
                    screenshot_path = self.logger.save_screenshot(
                        raw_screenshot, subtask_idx, step_count
                    )
                    if screenshot_path:
                        print(f"📸 Screenshot saved: {screenshot_path}")
                
                # 🆕 Store step details with enhanced information
                step_detail = {
                    "step": step_count,
                    "thought": thought,
                    "action": action,
                    "action_type": action_type,
                    "tool_call": tool_call,
                    "screenshot_path": screenshot_path,
                    # Model input and original output are no longer logged (too redundant)
                }
                
                # 🆕 If it is an ask type, add the question and answer
                if action_type == 'ask':
                    step_detail["question"] = question
                    step_detail["answer"] = answer
                
                # 🆕 If it is a dual model, add complete information
                if planner_reasoning or planner_instruction:
                    step_detail["planner_reasoning"] = planner_reasoning
                    step_detail["planner_instruction"] = planner_instruction
                    step_detail["executor_thought"] = executor_thought
                    step_detail["executor_action"] = executor_action
                elif dual_instruction:
                    step_detail["dual_instruction"] = dual_instruction
                
                step_details.append(step_detail)
                
                # Check if done
                if hasattr(response, 'done') and response.done:
                    done = True
                    completion_msg = "✓ Agent signaled completion"
                    print(f"\033[32m{completion_msg}\033[0m")  # Green color
                    self.logger.log(completion_msg)
                
                print()  # Empty line after each step
                self.logger.log("")
                
                # Wait after action
                await asyncio.sleep(2.0)
            
            except Exception as e:
                error_msg = f"⚠️  Step error: {e}"
                print(f"\033[31m{error_msg}\033[0m")  # Red color
                self.logger.log(error_msg)
                import traceback
                traceback_str = traceback.format_exc()
                self.logger.log(f"Traceback:\n{traceback_str}")
                break
        
        # 🆕 For QA tasks, check interaction_cache before evaluation
        if subtask.get('requires_answer'):
            debug_msg = f"\n{'='*80}\n🔍 PRE-EVALUATION DEBUG (QA Task)\n{'='*80}"
            print(debug_msg)
            self.logger.log(debug_msg)
            self.logger.log(f"interaction_cache type: {type(self.env.interaction_cache)}")
            self.logger.log(f"interaction_cache value: {repr(self.env.interaction_cache)[:300]}")
            
            # Check the action_type of the final step
            if step_details:
                last_step = step_details[-1]
                self.logger.log(f"Last step action_type: {last_step.get('action_type')}")
                self.logger.log(f"Last step tool_call: {last_step.get('tool_call', '')[:200]}")
            
            self.logger.log(f"{'='*80}\n")
        
        # Evaluate subtask
        eval_msg = f"\n{'='*80}\n📊 Evaluating subtask...\n{'='*80}"
        print(eval_msg)
        self.logger.log(eval_msg)
        
        # 🆕 Set up logging handler to capture evaluator log output
        import io
        import sys
        
        # Create string buffer to capture logs
        log_capture_stream = io.StringIO()
        log_handler = logging.StreamHandler(log_capture_stream)
        log_handler.setLevel(logging.INFO)
        log_formatter = logging.Formatter('%(message)s')
        log_handler.setFormatter(log_formatter)
        
        # Add handler
        root_logger = logging.getLogger()
        old_level = root_logger.level
        root_logger.setLevel(logging.INFO)
        root_logger.addHandler(log_handler)
        
        # Run blocking evaluate_subtask in executor (it's not async)
        loop = asyncio.get_event_loop()
        score = await loop.run_in_executor(
            None,
            evaluator.evaluate_subtask,
            subtask_idx,
            self.env
        )
        
        # Remove handler and retrieve logs
        root_logger.removeHandler(log_handler)
        root_logger.setLevel(old_level)
        evaluation_logs = log_capture_stream.getvalue()
        log_capture_stream.close()
        
        # 🆕 Also write evaluation logs to file
        if evaluation_logs:
            self.logger.log("\n--- Evaluation Details ---")
            self.logger.log(evaluation_logs)
            self.logger.log("--- End Evaluation Details ---\n")
        
        success = score >= 0.8
        
        # 📊 Get ask statistics (if the agent supports it)
        ask_count = 0
        total_steps = step_count  # Default to execution steps
        if hasattr(agent, 'ask_count'):
            ask_count = agent.ask_count
        if hasattr(agent, 'total_steps'):
            total_steps = agent.total_steps
        
        return {
            "name": subtask.get("evaluator_name", f"Subtask {subtask_idx + 1}"),
            "success": success,
            "score": score,
            "steps": step_count,
            "step_details": step_details,  # Include detailed step information
            "details": f"Completed in {step_count} steps",
            "ask_count": ask_count,  # 📊 Add number of questions asked
            "total_steps": total_steps,  # 📊 Add total steps (including ask steps)
        }
    
    def generate_summary_report(self):
        """Generate and save summary report for all scenarios."""
        print("\n" + "="*80)
        print("📋 BATCH TEST SUMMARY")
        print("="*80)
        print(f"Agent: {self.agent_type}")
        print(f"Total Scenarios: {len(self.results)}")
        print("="*80 + "\n")
        
        # Calculate statistics
        total_passed = sum(1 for r in self.results if r.get('success', False))
        avg_score = sum(r.get('score', 0.0) for r in self.results) / len(self.results) if self.results else 0.0
        
        print(f"✅ Passed: {total_passed}/{len(self.results)}")
        print(f"📊 Average Score: {avg_score:.2f}")
        print(f"📈 Success Rate: {total_passed/len(self.results)*100:.1f}%\n")
        
        # Detailed results
        print("Detailed Results:")
        print("-" * 80)
        for result in self.results:
            status = "✅" if result.get('success', False) else "❌"
            scenario = result.get('scenario', 'Unknown')
            score = result.get('score', 0.0)
            print(f"{status} {scenario:15s} | Score: {score:.2f} | {result.get('name', '')}")
        print("-" * 80 + "\n")
        
        # Save summary to JSON
        timestamp = datetime.datetime.now().strftime('%Y%m%d_%H%M%S')
        summary_file = self.logger.log_dir / f"summary-{self.agent_type}-{timestamp}.json"
        
        summary_data = {
            "agent": self.agent_type,
            "timestamp": timestamp,
            "clarity_level": self.clarity_level,
            "total_scenarios": len(self.results),
            "passed": total_passed,
            "average_score": avg_score,
            "success_rate": total_passed/len(self.results) if self.results else 0.0,
            "results": self.results,
        }
        
        with open(summary_file, 'w', encoding='utf-8') as f:
            json.dump(summary_data, f, indent=2, ensure_ascii=False)
        
        print(f"💾 Summary saved to: {summary_file}\n")
    
    def cleanup(self):
        """Cleanup resources."""
        if self.env:
            print("🧹 Cleaning up environment...")
            # Note: Add proper cleanup if needed
    
    def _check_layered_support(self, evaluator) -> bool:
        """Check if scenario supports layered instructions (L0/L1/L2).
        
        Args:
            evaluator: Scenario evaluator instance
        
        Returns:
            True if scenario has L0/L1/L2 instructions, False otherwise
        """
        # Check if evaluator has subtasks
        if not hasattr(evaluator, 'subtasks') or len(evaluator.subtasks) == 0:
            return False
        
        # Check first subtask for layered instructions
        first_subtask = evaluator.subtasks[0]
        has_l0 = 'user_instruction_L0' in first_subtask
        has_l1 = 'user_instruction_L1' in first_subtask
        has_l2 = 'user_instruction_L2' in first_subtask
        
        return has_l0 and has_l1 and has_l2
    
    @staticmethod
    def _find_adb_directory() -> str:
        """Returns the directory where adb is located."""
        potential_paths = [
            os.path.expanduser('~/Library/Android/sdk/platform-tools/adb'),
            os.path.expanduser('~/Android/Sdk/platform-tools/adb'),
        ]
        for path in potential_paths:
            if os.path.isfile(path):
                return path
        raise EnvironmentError('adb not found in the common Android SDK paths.')


# ============================================================
# Main Entry Point
# ============================================================

def parse_args():
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description="Batch testing for Scenario-Level evaluation",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__
    )
    
    parser.add_argument(
        "--agent",
        type=str,
        required=True,
        help="Agent type (e.g., qwen3vl-235b, doubao, qwen2.5vl-dual)"
    )
    
    parser.add_argument(
        "--scenarios",
        nargs="+",
        default=DEFAULT_SCENARIO_ORDER,
        help="Scenario list in order (e.g., a b c or omnilife e d)"
    )
    
    parser.add_argument(
        "--level",
        type=str,
        default=None,
        choices=["L0", "L1", "L2"],
        help="Clarity level for scenario instructions (default: None, use original instruction)"
    )
    
    parser.add_argument(
        "--auto_confirm",
        action="store_true",
        help="Auto-confirm all prompts"
    )
    
    parser.add_argument(
        "--log_dir",
        type=str,
        default="./scenario_logs",
        help="Directory to save logs (default: ./scenario_logs)"
    )
    
    parser.add_argument(
        "--console_port",
        type=int,
        default=5554,
        help="Emulator console port (default: 5554)"
    )
    
    parser.add_argument(
        "--grpc_port",
        type=int,
        default=8554,
        help="Emulator gRPC port (default: 8554)"
    )
    
    parser.add_argument(
        "--start_from_subtask",
        "--sub_task",  # 🆕 Add alias to support --sub_task
        type=int,
        default=None,
        dest="start_from_subtask",  # Both parameter names map to the same variable
        help="Start from specific subtask ID (e.g., 7 for Shopping task). Batch initialization still runs, but execution starts from this subtask. Useful for debugging specific tasks."
    )
    
    parser.add_argument(
        "--reset_mode",
        action="store_true",
        help="⚡ Enable Per-Task Reset Mode (comparative experiment): Each task is independently initialized with L0 instructions, with no state persistence and no task dependencies. Similar to traditional atomic task benchmarks like AndroidWorld."
    )
    
    return parser.parse_args()


async def main_async():
    """Async main function."""
    args = parse_args()
    
    # Validate scenarios
    invalid_scenarios = [s for s in args.scenarios if s.lower() not in SCENARIO_MAP]
    if invalid_scenarios:
        print(f"❌ Invalid scenarios: {', '.join(invalid_scenarios)}")
        print(f"Valid scenarios: {', '.join(SCENARIO_MAP.keys())}")
        sys.exit(1)
    
    # Normalize scenario names
    scenarios = [s.lower() for s in args.scenarios]
    
    # Create runner
    runner = ScenarioTestRunner(
        agent_type=args.agent,
        scenarios=scenarios,
        clarity_level=args.level,
        auto_confirm=args.auto_confirm,
        console_port=args.console_port,
        grpc_port=args.grpc_port,
        start_from_subtask=args.start_from_subtask,
        reset_mode=args.reset_mode  # ⚡ Per-Task Reset mode
    )
    
    try:
        # Initialize
        await runner.initialize()
        
        # Run all scenarios
        await runner.run_all_scenarios()
        
        # Generate summary
        runner.generate_summary_report()
    
    except KeyboardInterrupt:
        print("\n\n⚠️  Interrupted by user (Ctrl+C)")
        print("📝 All logs have been saved in real-time to disk")
        # Ensure logger file handles are closed
        if hasattr(runner, 'logger') and runner.logger.log_file_handle:
            runner.logger.log("\n[INTERRUPTED] Test interrupted by user")
            runner.logger.log_file_handle.close()
            runner.logger.log_file_handle = None
        if hasattr(runner, 'logger') and runner.logger.markdown_file_handle:  # 🆕 Close markdown
            runner.logger.markdown_file_handle.close()
            runner.logger.markdown_file_handle = None
        if hasattr(runner, 'logger'):
            print(f"💾 Current log file: {runner.logger.current_log_file}")
            if runner.logger.markdown_file:
                print(f"📝 Markdown report: {runner.logger.markdown_file}")
    
    except Exception as e:
        print(f"\n\n❌ Fatal error: {e}")
        import traceback
        traceback.print_exc()
        # Ensure logger file handles are closed
        if hasattr(runner, 'logger') and runner.logger.log_file_handle:
            runner.logger.log(f"\n[ERROR] Fatal error: {e}")
            runner.logger.log_file_handle.close()
            runner.logger.log_file_handle = None
        if hasattr(runner, 'logger') and runner.logger.markdown_file_handle:  # 🆕 Close markdown
            runner.logger.markdown_file_handle.close()
            runner.logger.markdown_file_handle = None
    
    finally:
        runner.cleanup()


def main():
    """Main entry point."""
    asyncio.run(main_async())


if __name__ == "__main__":
    main()
